export const opportunities = [
  {
    id: "1",
    title: "Senior React Developer",
    organization: "Facebook",
    source_platform: "LinkedIn",
    deadline: "2026-12-31",
    priority: "High",
    url: "https://www.linkedin.com/jobs/view/123456789",
  },
  {
    id: "2",
    title: "Project Manager",
    organization: "Google",
    source_platform: "Devex",
    deadline: "2026-11-30",
    priority: "Medium",
    url: "https://www.devex.com/jobs/project-manager-12345",
  },
  {
    id: "3",
    title: "Data Scientist",
    organization: "Amazon",
    source_platform: "Impactpool",
    deadline: "2027-01-15",
    priority: "High",
    url: "https://www.impactpool.org/jobs/123456",
  },
  {
    id: "4",
    title: "UX/UI Designer",
    organization: "Microsoft",
    source_platform: "UNDP",
    deadline: "2026-12-01",
    priority: "Low",
    url: "https://jobs.undp.org/cj_view_job.cfm?job_id=123456",
  },
  {
    id: "5",
    title: "Backend Engineer",
    organization: "Netflix",
    source_platform: "World Bank",
    deadline: "2027-02-01",
    priority: "Medium",
    url: "https://www.worldbank.org/en/about/jobs/all",
  },
];
